import { useEffect, useMemo, useState } from 'react';
import { apiFetch } from '../api/apiClient';
import HomePage from './HomePage';

const blankProfile = { nic: '', fullName: '', email: '', phoneNumber: '', password: '' };
const blankStaff = { ...blankProfile, role: 'GridOperator' };

function ProfileForm({ value, onChange, onSubmit, busy, includeRole = false, submitLabel = 'Create staff' }) {
  return <form className="row g-2" onSubmit={onSubmit}>
    <div className="col-md-6"><input required className="form-control" name="nic" placeholder="NIC" value={value.nic} onChange={onChange} /></div>
    <div className="col-md-6"><input required className="form-control" name="fullName" placeholder="Full name" value={value.fullName} onChange={onChange} /></div>
    <div className="col-md-6"><input required className="form-control" type="email" name="email" placeholder="Email" value={value.email} onChange={onChange} /></div>
    <div className="col-md-6"><input required className="form-control" name="phoneNumber" placeholder="Phone number" value={value.phoneNumber} onChange={onChange} /></div>
    <div className="col-md-6"><input required className="form-control" type="password" name="password" minLength="8" placeholder="Password (8+ characters)" value={value.password} onChange={onChange} /></div>
    {includeRole && <div className="col-md-6"><select className="form-select" name="role" value={value.role} onChange={onChange}><option value="GridOperator">GridOperator</option><option value="Backoffice">Backoffice</option></select></div>}
    <div className="col-12"><button className="btn btn-primary w-100" disabled={busy}>{submitLabel}</button></div>
  </form>;
}

export default function UserManagementPage() {
  const [users, setUsers] = useState([]); const [staff, setStaff] = useState(blankStaff); const [prosumer, setProsumer] = useState(blankProfile);
  const [editing, setEditing] = useState(null); const [query, setQuery] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const load = async () => { setBusy(true); setError(''); try { setUsers(await apiFetch('/users')); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  useEffect(() => { load(); }, []);
  const update = (setter, value) => e => setter({ ...value, [e.target.name]: e.target.value });
  const shown = useMemo(() => users.filter(u => `${u.nic} ${u.fullName} ${u.email} ${u.role} ${u.status}`.toLowerCase().includes(query.toLowerCase())), [users, query]);
  const pending = users.filter(u => u.role === 'Prosumer' && u.status === 'PendingActivation');
  const submit = async (event, path, value, successText, reset) => { event.preventDefault(); setBusy(true); setError(''); setMessage(''); try { await apiFetch(path, { method: 'POST', body: JSON.stringify(value) }); reset(); setMessage(successText); await load(); } catch (e) { setError(e.message); setBusy(false); } };
  const statusChange = async (user, action) => { setBusy(true); setError(''); setMessage(''); try { await apiFetch(`/users/${encodeURIComponent(user.nic)}/${action}`, { method: 'PATCH' }); setMessage(`${user.fullName}'s account was ${action === 'activate' ? 'activated' : 'deactivated'}.`); await load(); } catch (e) { setError(e.message); setBusy(false); } };
  const saveProsumer = async event => { event.preventDefault(); setBusy(true); setError(''); try { await apiFetch(`/users/${encodeURIComponent(editing.nic)}`, { method: 'PUT', body: JSON.stringify(editing) }); setEditing(null); setMessage('Prosumer profile updated.'); await load(); } catch (e) { setError(e.message); setBusy(false); } };
  return <HomePage><div className="container py-4"><div className="d-flex flex-wrap gap-3 justify-content-between align-items-start mb-4"><div><p className="eyebrow">BACKOFFICE</p><h1>User management</h1><p className="text-secondary mb-0">Manage staff, Prosumer profiles and pending activation.</p></div><button className="btn btn-outline-primary" disabled={busy} onClick={load}>Refresh</button></div>
    {error && <div className="alert alert-danger" role="alert">{error}</div>}{message && <div className="alert alert-success" role="status">{message}</div>}
    <div className="row g-4 mb-4"><section className="col-lg-6"><div className="card h-100 p-3"><h2 className="h5">Create staff user</h2><p className="small text-secondary">Creates an active Backoffice or GridOperator account.</p><ProfileForm value={staff} onChange={update(setStaff, staff)} onSubmit={e => submit(e, '/users/staff', staff, 'Staff account created.', () => setStaff(blankStaff))} busy={busy} includeRole /></div></section><section className="col-lg-6"><div className="card h-100 p-3"><h2 className="h5">Register Prosumer</h2><p className="small text-secondary">Creates a PendingActivation account for Backoffice review.</p><ProfileForm value={prosumer} onChange={update(setProsumer, prosumer)} onSubmit={e => submit(e, '/auth/register-prosumer', prosumer, 'Prosumer registered and added to pending activation.', () => setProsumer(blankProfile))} busy={busy} submitLabel="Register Prosumer" /></div></section></div>
    <section className="card p-3 mb-4"><h2 className="h5">Pending Prosumer activation</h2>{pending.length ? <div className="table-responsive"><table className="table align-middle mb-0"><thead><tr><th>NIC</th><th>Prosumer</th><th>Contact</th><th>Action</th></tr></thead><tbody>{pending.map(u => <tr key={u.nic}><td>{u.nic}</td><td>{u.fullName}</td><td>{u.email}<small className="d-block text-secondary">{u.phoneNumber}</small></td><td><button className="btn btn-sm btn-success" disabled={busy} onClick={() => statusChange(u, 'activate')}>Activate</button></td></tr>)}</tbody></table></div> : <p className="text-secondary mb-0">No Prosumer accounts are waiting for activation.</p>}</section>
    {editing && <section className="card p-3 mb-4"><h2 className="h5">Edit Prosumer: {editing.nic}</h2><p className="small text-secondary">NIC, role, account status and password cannot be changed here.</p><form className="row g-2" onSubmit={saveProsumer}><div className="col-md-4"><input required className="form-control" name="fullName" value={editing.fullName} onChange={update(setEditing, editing)} /></div><div className="col-md-4"><input required className="form-control" type="email" name="email" value={editing.email} onChange={update(setEditing, editing)} /></div><div className="col-md-4"><input required className="form-control" name="phoneNumber" value={editing.phoneNumber} onChange={update(setEditing, editing)} /></div><div className="col-12 d-flex gap-2"><button className="btn btn-primary" disabled={busy}>Save Prosumer</button><button type="button" className="btn btn-outline-secondary" disabled={busy} onClick={() => setEditing(null)}>Cancel</button></div></form></section>}
    <section className="card p-3"><div className="d-flex flex-wrap gap-3 justify-content-between mb-3"><h2 className="h5 mb-0">All accounts</h2><input className="form-control w-auto" aria-label="Search accounts" placeholder="Search accounts" value={query} onChange={e => setQuery(e.target.value)} /></div><div className="table-responsive"><table className="table align-middle"><thead><tr><th>NIC</th><th>Name</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{shown.map(u => <tr key={u.nic}><td>{u.nic}</td><td>{u.fullName}<small className="d-block text-secondary">{u.email}</small></td><td>{u.role}</td><td>{u.status}</td><td className="d-flex flex-wrap gap-2">{u.role === 'Prosumer' && <button className="btn btn-sm btn-outline-primary" disabled={busy} onClick={() => setEditing(u)}>Edit</button>}{u.status === 'Active' ? <button className="btn btn-sm btn-outline-danger" disabled={busy} onClick={() => statusChange(u, 'deactivate')}>Deactivate</button> : <button className="btn btn-sm btn-outline-success" disabled={busy} onClick={() => statusChange(u, 'activate')}>{u.status === 'PendingActivation' ? 'Activate' : 'Reactivate'}</button>}</td></tr>)}</tbody></table>{!busy && !shown.length && <p className="text-secondary mb-0">No matching accounts.</p>}</div></section>
  </div></HomePage>;
}
